eureka:
  client:
    service-url:
      defaultZone: http://192.168.56.171:8761/eureka/
spring:
  application:
    name: tuanzi-order-test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.56.179/test_eureka?characterEncoding=utf-8&useSSL=false
server:
  port: 8765
env:
  dev
